# 配置文件样例和说明
#
# 本地开发将该文件复制一份并重命名为 config.toml 文件配置自己的数据库连接等信息
# 该文件为个人私有不提交到仓库, 因为代码库是开源的, 涉及到一些隐私信息无法将配置文件原样提交到仓库中
# 部署环境会提前准备好其它的环境变量配置信息

# 服务监听地址和端口配置
[server]
host = "0.0.0.0"
port = 8082

# 数据库连接信息
[database]
url = "postgres://tiku_rw:123456@localhost/open_tiku_test"
web_max_connections = 2
task_max_connections = 2

# 图片等资源存储路径
[meta]
path = "/var/data/meta"

# 登录相关
[login]
# 网站首页, 目前第三方跳转登录后跳转到首页
website_home_url = "http://tiku.test"
# oauth 第三方登录校验 state 安全密钥值
oauth_state_secret = ""
# 生成学生账户密码的 胡椒 值
student_pepper = ""

# GitHub 登录认证配置, 固定配置的, 需要登录 GitHub 去获取
[login.github]
client_id = ""
client_secret = ""
redirect_uri = "http://tiku.test/api/callback/github"

# QQ 登录认证配置, 固定配置的, 需要跟其它伙伴获取
[login.qq]
client_id = ""
client_secret = ""
redirect_uri = "http://tiku.test/api/callback/qq"

# SMTP 邮箱发送服务配置
[smtp]
server = "smtp.qq.com"
port = 587
username = ""
password = ""
from_name = ""
from_email = ""
